version: '3.9'
services:
  webserver-1:
    build:
      context: ./.docker/server_http/
    environment:
      - HOOS_CTF_USERNAME=${HOOS_CTF_USERNAME:-}
    labels:
      ho.ctf.cyrhades: "1"
    ports:
      - ${PORT}:80